<?php

namespace modava\product\models\table;

use cheatsheet\Time;
use modava\product\models\query\ProductCategoryQuery;
use Yii;

/**
 * This is the model class for table "product_category".
 *
 * @property int $id
 * @property string $title
 * @property string $slug
 * @property int|null $parent_id
 * @property string|null $image
 * @property string|null $description
 * @property int|null $position
 * @property string|null $ads_pixel
 * @property string|null $ads_session
 * @property int $status
 * @property string $language
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 */
class ProductCategoryTable extends \yii\db\ActiveRecord
{
    const STATUS_PUBLISHED = 1;
    const STATUS_DISABLED = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product_category';
    }

    public static function find()
    {
        return new ProductCategoryQuery(get_called_class());
    }

    public static function getById($id, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-product-category-table-get-by-id-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where([self::tableName() . '.id' => $id, self::tableName() . '.language' => $language])->published()->one();
            $cache->set($key, $data, Time::SECONDS_IN_A_MONTH);
        }
        return $data;
    }

    public static function getAllProductCategory($lang = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-all-product-category-' . $lang;

        $data = $cache->get($key);

        if ($data === false) {
            $data = self::find()->where(['language' => $lang])->published()->sortDescById()->all();
            $cache->set($key, $data, Time::SECONDS_IN_A_MONTH);
        }

        return $data;
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-get-all-product-category-' . $this->language,
            'redis-product-category-table-get-by-id-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        $cache->delete($key);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-get-all-product-category-' . $this->language,
            'redis-product-category-table-get-by-id-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        $cache->delete($key);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
