<?php

namespace modava\product\models\table;

use Yii;

/**
 * This is the model class for table "product_image".
 *
 * @property int $id
 * @property int $product_id
 * @property string $image_url
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 *
 */
class ProductImageTable extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static $upload_dir = '/uploads/filemanager/source/';
    public static $base_url;

    public function init()
    {
        self::$base_url = Yii::getAlias('@frontendUrl');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return 'product_image';
    }

    public static function getUploadDir()
    {
        return self::$upload_dir;
    }

    public static function getBaseUrl()
    {
        return self::$base_url;
    }

    public function getImage(string $size = null)
    {
        $image = $this->image_url;
        if (!isset(Yii::$app->params['product'])) $image = 'no-image.png';
        if (!array_key_exists($size, Yii::$app->params['product'])) $size = array_keys(Yii::$app->params['product'])[0];
        $pathImage = Yii::getAlias('@frontend/web') . Yii::$app->params['product'][$size]['folder'];
        if (is_dir($pathImage . $image) || !file_exists($pathImage . $image)) $image = 'no-image.png';
        return Yii::$app->assetManager->publish($pathImage . $image)[1];
    }
}
