<?php

namespace modava\product\models\table;

use backend\components\MyModel;
use cheatsheet\Time;
use modava\product\models\query\ProductTypeQuery;
use Yii;

/**
 * This is the model class for table "product_type".
 *
 * @property int $id
 * @property string $title
 * @property string $slug
 * @property string|null $image
 * @property string|null $description
 * @property int|null $position
 * @property string|null $ads_pixel
 * @property string|null $ads_session
 * @property int $status
 * @property string $language Language
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 *
 * @property User $createdBy
 * @property User $updatedBy
 */
class ProductTypeTable extends MyModel
{
    const STATUS_PUBLISHED = 1;
    const STATUS_DISABLED = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product_type';
    }

    public static function find()
    {
        return new ProductTypeQuery(get_called_class());
    }

    public static function getAllProductType($lang = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-all-product-type-' . $lang;

        $data = $cache->get($key);

        if ($data === false) {
            $query = self::find();
            if ($lang != null)
                $query->where(['language' => $lang]);
            $data = $query->published()->sortDescById()->all();
            $cache->set($key, $data, Time::SECONDS_IN_A_MONTH);
        }

        return $data;
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $lang = $this->language;
        $key = 'redis-get-all-product-type-' . $lang;
        $cache->delete($key);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $lang = $this->language;
        $key = 'redis-get-all-product-type-' . $lang;
        $cache->delete($key);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
