<?php

namespace modava\product\controllers;

use modava\product\components\MyProductController;


class ProductController extends MyProductController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index', []);
    }
}
