<?php


namespace modava\product\components;


use backend\components\MyController;

class MyProductController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    protected function getUploadDir()
    {
        $uploadDir = \Yii::$app->getModule('product')->upload_dir;
        return \Yii::getAlias($uploadDir);
    }
}