<?php


namespace modava\product\components;


use backend\components\MyController;

class MyProductController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}